import javax.swing.JOptionPane;
public class Ceknomorganjilgenap extends javax.swing.JFrame {

    
    public Ceknomorganjilgenap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInput = new javax.swing.JLabel();
        txtAngka = new javax.swing.JTextField();
        lblHasil = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ceknomorganjilgenap");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInput.setText("Masukkan Angka");
        lblInput.setAlignmentX(150.0F);
        lblInput.setAlignmentY(60.0F);
        getContentPane().add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, 20));

        txtAngka.setAlignmentX(160.0F);
        txtAngka.setAlignmentY(90.0F);
        txtAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngkaActionPerformed(evt);
            }
        });
        getContentPane().add(txtAngka, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, -1));

        lblHasil.setText("Hasil akan muncul di sini");
        lblHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblHasilActionPerformed(evt);
            }
        });
        getContentPane().add(lblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        getContentPane().add(btnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAngkaActionPerformed

    private void lblHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHasilActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
try {
    int angka = Integer.parseInt(txtAngka.getText());
    String hasil;

    if (angka % 2 == 0) {
        hasil = angka + " adalah bilangan GENAP";
    } else {
        hasil = angka + " adalah bilangan GANJIL";
    }

    lblHasil.setText(hasil);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!",
            "Error", JOptionPane.ERROR_MESSAGE);    
    }//GEN-LAST:event_btnCekActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ceknomorganjilgenap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ceknomorganjilgenap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ceknomorganjilgenap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ceknomorganjilgenap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ceknomorganjilgenap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton lblHasil;
    private javax.swing.JLabel lblInput;
    private javax.swing.JTextField txtAngka;
    // End of variables declaration//GEN-END:variables
}
